<a href="https://colab.research.google.com/github/LINA078/Inteligencia_Artificial/blob/main/Segundo_Corte/Actividad-Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

INVESTIGACION SOBRE LA LIBRERIA PANDA EN PYTHON

LINA MARIA ALOMIA VIVEROS
INGENIERIA DE SISTEMAS
INTELIGENCIA ARTIFICIAL
19/05/26
.

##¿QUE ES PANDAS?


Pandas es una librería de Python utilizada para el análisis y la manipulación de datos. Permite trabajar con información organizada en tablas, parecidas a las hojas de cálculo de Excel.

Es una herramienta de código abierto, rápida, flexible y fácil de usar. Está construida sobre el lenguaje Python y se utiliza especialmente cuando se necesita limpiar, ordenar, analizar o transformar datos.
##¿PARA QUE SIRVE PANDAS?


Pandas sirve para trabajar con datos de manera organizada. Con esta librería se pueden realizar tareas como:

- Crear tablas de datos.
- Leer archivos CSV, Excel y otros formatos.
- Filtrar información.
- Realizar operaciones matemáticas entre columnas.
- Ordenar datos.
- Calcular promedios, sumas, máximos y mínimos.
- Limpiar datos incompletos o incorrectos.
- Preparar información para análisis de datos o modelos de Inteligencia Artificial.

En pocas palabras, Pandas permite convertir datos desordenados en información clara y útil para tomar decisiones.

##OBJETIVO PRINCIPAL DE LA LIBRERIA


El objetivo principal de Pandas es facilitar el trabajo con datos estructurados, es decir, datos organizados en filas y columnas.

Esta librería busca que el usuario pueda analizar datos reales de una forma más sencilla, rápida y comprensible. También permite manipular datos etiquetados o relacionales, lo que la convierte en una herramienta importante para el análisis práctico de información en Python.
##PRINCIPALES FUNCIONES Y CARACTERISITICAS

Pandas cuenta con varias funciones y características importantes:

1. **DataFrame:**  
   Es una estructura de datos en forma de tabla, con filas y columnas. Es una de las estructuras principales de Pandas. :contentReference

2. **Series:**  
   Es una estructura de una sola dimensión, parecida a una columna de una tabla. Puede contener números, textos u otros tipos de datos.

3. **Lectura de archivos:**  
   Permite importar archivos como CSV o Excel para analizarlos en Python.

4. **Filtrado de datos:**  
   Permite seleccionar solo la información que se necesita.

5. **Operaciones entre columnas:**  
   Se pueden hacer sumas, restas, multiplicaciones, divisiones y cálculos con los datos.

6. **Limpieza de datos:**  
   Ayuda a identificar valores vacíos, duplicados o incorrectos.

7. **Agrupación de datos:**  
   Permite organizar información por categorías, por ejemplo, calcular el promedio de notas por grupo.

##IMPORTANCIA DE PANDAS EN LA INTELIGENCIA ARTIFICIAL Y EL ANALISIS DE DATOS
   

Pandas es importante en la Inteligencia Artificial porque antes de entrenar un modelo, los datos deben estar limpios, organizados y preparados.

En muchos proyectos de Inteligencia Artificial, los datos vienen de archivos, encuestas, bases de datos o registros. Estos datos pueden tener errores, valores vacíos o información desordenada. Pandas ayuda a preparar esos datos para que puedan ser usados correctamente.

También es muy importante en el análisis de datos porque permite estudiar información, encontrar patrones, calcular estadísticas y obtener conclusiones. Por ejemplo, se puede usar para analizar las notas de estudiantes, ventas de una empresa, encuestas o datos de salud.

EJERCICIOS PRACTICOS CON PANDA
Acontinuacion voy a desarrollar ejercicios usando la libreria Pandas. Se creará un DataFrame con datos de productos, se realizaran operaciones entre columnas y se calcularan resultados.
En esta primera parte importo la libreria Pandas.
Uso pd como abreviatura para no escribir la palabra competa cada vez que utilice la libreria.

In [1]:
import pandas as pd

CREACION DE UN DATAFRAME
Aui se crea un DataFrame que es una tabla de datos. En este caso, la tabla contiene Nombre de Estudiantes, Nota 1, Nota 2, y Nota 3.

In [50]:
datos={"Estudiantes": ["Ana", "Lucas", "Carlos", "Maria", "Lucia"], "Nota_1": [60, 56, 48, 74, 65],
       "Nota_2":[100, 70,65,90,60],
       "Nota_3":[60,85,54,55,98]

       }
df =pd.DataFrame(datos)
df

  Estudiantes  Nota_1  Nota_2  Nota_3
0         Ana      60     100      60
1       Lucas      56      70      85
2      Carlos      48      65      54
3       Maria      74      90      55
4       Lucia      65      60      98

OPERACIONES ENTRE COLUMNAS
En esta parte voy a calcular el promedio de cada estudiante usando sus tres notas.
Hice una operacion entre columnas. Sume las tres notas de cada estudiante y luego dividi el resultado entre 3

In [51]:
df["Promedio"]= (df["Nota_1"] +  df["Nota_2"] + df["Nota_3"])/3
df

  Estudiantes  Nota_1  Nota_2  Nota_3   Promedio
0         Ana      60     100      60  73.333333
1       Lucas      56      70      85  70.333333
2      Carlos      48      65      54  55.666667
3       Maria      74      90      55  73.000000
4       Lucia      65      60      98  74.333333


##PROMEDIO GENERAL DEL GRUPO
Aqui voy calcular el promedio general de todo los estudiantes.
aqui utilizare la funcion mean(), que sirve para calcular el promedio. En este caso, estoy calculando el promedio de todos los valores que estan en la column a promedio.
Esto me permite saber cual fue el rendimiento general de todo el grupo.

In [56]:
Promedio_General=df["Promedio"].mean()
print("EL PROMEDIO GENERAL DEL GRUPO ES:" ,
Promedio_General)

EL PROMEDIO GENERAL DEL GRUPO ES: 69.33333333333333

##CALCULAR LA SUMA TOTAL DE LOS PROMEDIOS
Aqui calcule el promedio general del grupo usando la columna "Promedio". La funcion mean() sirve para sacar el promedio de los valores de una columna.

In [62]:
promedio_grupal = df["Promedio"].mean()

print("El promedio grupal es:", promedio_grupal )

El promedio grupal es: 69.33333333333333

##DETERMINAR SI CADA ESTUDIANTE APRUEBA O NO APRUEBA
En esta parte agregue una columna llamada "Resultado. Si el promedio es mayor o igual a 60, aparece "Aprueba si el promedio es menor que 60,aparece "No aprueba".
la parte lambda sirve para revisar cada promedio y decidir si el estudiante aprueba o no aprueba

In [66]:
df["Resultado"] = df["Promedio"].apply(
    lambda x: "Aprueba" if x >= 60 else "No aprueba"
)

df

  Estudiantes  Nota_1  Nota_2  Nota_3   Promedio   Resultado
0         Ana      60     100      60  73.333333     Aprueba
1       Lucas      56      70      85  70.333333     Aprueba
2      Carlos      48      65      54  55.666667  No aprueba
3       Maria      74      90      55  73.000000     Aprueba
4       Lucia      65      60      98  74.333333     Aprueba

ESTADISTICAS BASICAS
En este paso se calcule estadísticas básicas del grupo. Primero obtuve el promedio general usando la función mean(). Despues identifiqué el estudiante con el promedio más alto utilizando idxmax(), que permite ubicar la fila donde esta la nota mayor.
Tambien identifiqué el estudiante cob el promedio mas bajo usando idxmin(), que permite ubicar la fila donde esta la nota menor, finalmente, imprime los resultados mostrando el nombre del estudiante y su respectivo promedio

In [69]:
Promedio_General = df["Promedio"].mean()

Estudiante_Mayor = df.loc[df["Promedio"].idxmax(), "Estudiantes"]
Nota_Mayor = df["Promedio"].max()

Estudiante_Menor = df.loc[df["Promedio"].idxmin(), "Estudiantes"]
Nota_Menor = df["Promedio"].min()

print("El promedio general del grupo es:", round(Promedio_General, 2))
print("El estudiante con mayor promedio es:", Estudiante_Mayor, "con una nota de:", round(Nota_Mayor, 2))
print("El estudiante con menor promedio es:", Estudiante_Menor, "con una nota de:", round(Nota_Menor, 2))

El promedio general del grupo es: 69.33
El estudiante con mayor promedio es: Lucia con una nota de: 74.33
El estudiante con menor promedio es: Carlos con una nota de: 55.67

CREAR UN ARCHIVO CSV
Aquí guarde la tabla  en un archivo CSV llamado NOtas_Estudiantes.csv.

In [74]:
df.to_csv("Notas_Estudiantes.csv" ,
index=False)

LEER ARCHIVO CSV
Ahora se lee el archivo CSV creado anteriormente. Esto permite comprobar que el archivo fue creado correctamente

In [75]:
Archivo_Notas = pd.read_csv("Notas_Estudiantes.csv")

Archivo_Notas

  Estudiantes  Nota_1  Nota_2  Nota_3   Promedio   Resultado
0         Ana      60     100      60  73.333333     Aprueba
1       Lucas      56      70      85  70.333333     Aprueba
2      Carlos      48      65      54  55.666667  No aprueba
3       Maria      74      90      55  73.000000     Aprueba
4       Lucia      65      60      98  74.333333     Aprueba

DATOS SINTETICOS
En este paso creé un DataFrame con datos sinteticos de productos
La columna "Producto" contiene los nombres de productos. La columna "Cantidad_Vendida" muestra cuantas unidades se vendieron de cada producto. La columna "Precio" indica el valor unitario de cada producto.
Estos datos son sinteticos porque fueron inventados para realizar el ejercicio y practicar como pandas permite organizar informacion en forma de tabla.

In [80]:
import pandas as pd

Datos_Sinteticos = {
    "Producto": ["Camisa" , "Pantalon" , "Zapatos", "Bolso", "Gorra"],
    "Precio": [35000 , 60000, 40000, 12000 , 55000] ,
    "Cantidad_Vendida" : [20,8,18,6,45]
}
Ventas=pd.DataFrame(Datos_Sinteticos)

Ventas

   Producto  Precio  Cantidad_Vendida
0    Camisa   35000                20
1  Pantalon   60000                 8
2   Zapatos   40000                18
3     Bolso   12000                 6
4     Gorra   55000                45

OPERACIÓN ENTRE CONLUMNAS CON DATOS SINTÉTICOS
En este paso se calcula el total de venta de cada producto multiplicando el precio por la cantidad vendida.

In [84]:
Ventas["Total_Vendido"] = Ventas["Cantidad_Vendida"] * Ventas["Precio"]

Ventas

   Producto  Precio  Cantidad_Vendida  Total_Vendido
0    Camisa   35000                20         700000
1  Pantalon   60000                 8         480000
2   Zapatos   40000                18         720000
3     Bolso   12000                 6          72000
4     Gorra   55000                45        2475000

##CALCULAR EL TOTAL GENERAL DE VENTAS
Aqui calcule el total general de ventas usando la funcion sum(). Esta función suma todos los valores de la columna "Total_Vendido"
Con este resultado puedo saner cuánto dinero se vendio en total con todos los productos.

In [89]:
total_general = Ventas["Total_Vendido"].sum()

print("EL TOTAL GENERAL DE VENTAS ES:", total_general)

EL TOTAL GENERAL DE VENTAS ES: 4447000

##IDENTIFICAR EL PRODUCTO MAS VENDIDO
En este caso identifique cuál fue el producto con mayor cantidad vendida para eso use idxmax(), que permite encontrar la fila donde esta el valor mas alto.
Despues mostre el nombre del producto más vendido y la cantidad de unidades vendidas.

In [91]:
Producto_Mas_Vendido = Ventas.loc[Ventas["Cantidad_Vendida"].idxmax(),"Producto"]
Cantidad_Mayor = Ventas["Cantidad_Vendida"].max()
print("EL PRODUCTO MAS VENDIDO ES:" , Producto_Mas_Vendido, " CON", Cantidad_Mayor, "UNIDADES VENDIDAS")

EL PRODUCTO MAS VENDIDO ES: Gorra  CON 45 UNIDADES VENDIDAS

##IDENTIFICAR EL PRODUCTO MENOS VENDIDO
En este paso identifique cuál fue el producto con menor cantidad vendida. para eso utilice idxmin(), que permite encontrar la fila donde esta el valor mas bajo.
luego imprimi el nombre del producto menos vendido y la cantidad correspondienre.

In [93]:
Producto_Menos_Vendido = Ventas.loc[Ventas["Cantidad_Vendida"].idxmin(),"Producto"]
Cantidad_Menor = Ventas["Cantidad_Vendida"].min(),
print("EL PRODUCTO Menos VENDIDO ES:" , Producto_Menos_Vendido, " CON", Cantidad_Menor, "UNIDADES VENDIDAS")

EL PRODUCTO Menos VENDIDO ES: Bolso  CON (6,) UNIDADES VENDIDAS

##CREAR ARCHIVO CSV
En esta parte guarda el DataFrame en un archivo llamado "Ventas.csv
El archivo CSV permite guardar los datos en forna de tabla para poder usarlos despues. El parametro index=False sirve para que no se guarde una columna adicional con los numeros del indice.

In [96]:
Ventas.to_csv("Ventas.csv", index=False)
print("EL ARCHIVO CSV FUE CREADO CORRECTAMENTE,")

EL ARCHIVO CSV FUE CREADO CORRECTAMENTE,

##LEER ARCHIVO CSV
Aqui lei el archivo CSV que habia creado anteriormente. Esto permite comprobar que la información fue guardada correctamente y que puede volver a cargarse en panda

In [97]:
Archivo_Ventas = pd.read_csv("Ventas.csv")
Archivo_Ventas

   Producto  Precio  Cantidad_Vendida  Total_Vendido
0    Camisa   35000                20         700000
1  Pantalon   60000                 8         480000
2   Zapatos   40000                18         720000
3     Bolso   12000                 6          72000
4     Gorra   55000                45        2475000

##CONCLUSIÓN
En esta actividad aprendi a utulizar la libreria pandas para organizar y analizar datos en python. Realicé ejercicios con DataFrames, operaciones entre columnas, datos sinteticos y archivos CSV. Esto me permitio comprender que Pandas es una herramienta importante porque facilita el manejo de información y permite obtener resultados de forma clara y rápida.